[package]
name = "dolos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actionidmap-updater = "0.2.0"
nanoserde = "0.1.32"
regex = "1.8.4"
